import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { getCurrentOrganization, listDepartments, listEmployees, type Department, type Organization } from "@/lib/workspace";

export const Route = createFileRoute("/app/departments")({ component: DepartmentsPage });

function DepartmentsPage() {
  const [org,setOrg]=useState<Organization|null>(null); const [departments,setDepartments]=useState<Department[]>([]); const [counts,setCounts]=useState<Record<string,number>>({}); const [name,setName]=useState(""); const [description,setDescription]=useState(""); const [message,setMessage]=useState("");
  async function refresh(){ const current=await getCurrentOrganization(); setOrg(current); if(!current){setMessage("No workspace is available yet. Apply the Phase 1 Supabase migration, then refresh this page.");return;} const [deps,people]=await Promise.all([listDepartments(current.id),listEmployees(current.id)]); setDepartments(deps); const next:Record<string,number>={}; people.forEach(e=>{if(e.department_id)next[e.department_id]=(next[e.department_id]||0)+1}); setCounts(next); }
  useEffect(()=>{refresh().catch(e=>setMessage(e.message))},[]);
  async function add(){ if(!name.trim()){setMessage("Enter a department name first.");return;} if(!org){setMessage("Cannot create the department because no workspace is loaded. Apply the Phase 1 Supabase migration, then refresh this page.");return;} const {error}=await supabase.from("departments").insert({organization_id:org.id,name:name.trim(),description:description.trim()||null}); if(error)throw error; setName("");setDescription("");setMessage("Department created.");await refresh(); }
  async function remove(id:string){ const {error}=await supabase.from("departments").delete().eq("id",id); if(error)throw error; setMessage("Department deleted. Employees were kept and are now unassigned.");await refresh(); }
  return <div className="p-8 max-w-5xl mx-auto"><div className="flex justify-between items-start mb-8"><div><p className="text-xs uppercase tracking-widest text-muted-foreground mb-2">People</p><h1 className="text-3xl font-semibold">Departments</h1><p className="text-muted-foreground mt-2">Organize employees for signature targeting and future deployment rules.</p></div><Link to="/app/employees" className="px-4 py-2 border rounded-lg text-sm">Employees</Link></div>{message&&<div className="mb-4 p-3 bg-secondary rounded-lg text-sm">{message}</div>}<div className="grid md:grid-cols-[1fr_340px] gap-6"><div className="border rounded-xl bg-white overflow-hidden">{departments.map(d=><div key={d.id} className="p-5 border-b last:border-b-0 flex justify-between gap-4"><div><div className="font-medium">{d.name}</div><div className="text-sm text-muted-foreground">{d.description||"No description"} · {counts[d.id]||0} employees</div></div><button onClick={()=>remove(d.id).catch(e=>setMessage(e.message))} className="text-sm text-muted-foreground hover:text-foreground">Delete</button></div>)}{!departments.length&&<div className="p-10 text-center text-muted-foreground">No departments yet.</div>}</div><div className="border rounded-xl bg-white p-5 h-fit"><h2 className="font-semibold mb-4">New department</h2><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Sales" className="w-full border rounded-lg px-3 py-2 mb-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Optional description" className="w-full border rounded-lg px-3 py-2 mb-3 min-h-24"/><button onClick={()=>add().catch(e=>setMessage(e.message))} className="w-full px-4 py-2 bg-foreground text-background rounded-lg">Create department</button></div></div></div>;
}
