/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AppEditorIdRouteImport } from './routes/app.editor.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AppEditorIdIndexRouteImport } from './routes/app.editor.$id.index'
import { Route as AppEditorIdSocialRouteImport } from './routes/app.editor.$id.social'
import { Route as AppEditorIdDisclaimerRouteImport } from './routes/app.editor.$id.disclaimer'
import { Route as AppEditorIdDetailsRouteImport } from './routes/app.editor.$id.details'
import { Route as AppEditorIdDesignRouteImport } from './routes/app.editor.$id.design'
import { Route as AppEditorIdCtaRouteImport } from './routes/app.editor.$id.cta'
import { Route as AppEditorIdBusinessRouteImport } from './routes/app.editor.$id.business'
import { Route as AppEditorIdAnalyticsRouteImport } from './routes/app.editor.$id.analytics'
import { Route as ApiPublicSigImageIdKindRouteImport } from './routes/api/public/sig-image.$id.$kind'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppEditorIdRoute = AppEditorIdRouteImport.update({
  id: '/editor/$id',
  path: '/editor/$id',
  getParentRoute: () => AppRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEditorIdIndexRoute = AppEditorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdSocialRoute = AppEditorIdSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdDisclaimerRoute = AppEditorIdDisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdDetailsRoute = AppEditorIdDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdDesignRoute = AppEditorIdDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdCtaRoute = AppEditorIdCtaRouteImport.update({
  id: '/cta',
  path: '/cta',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdBusinessRoute = AppEditorIdBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const AppEditorIdAnalyticsRoute = AppEditorIdAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppEditorIdRoute,
} as any)
const ApiPublicSigImageIdKindRoute = ApiPublicSigImageIdKindRouteImport.update({
  id: '/api/public/sig-image/$id/$kind',
  path: '/api/public/sig-image/$id/$kind',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/editor/$id': typeof AppEditorIdRouteWithChildren
  '/app/editor/$id/analytics': typeof AppEditorIdAnalyticsRoute
  '/app/editor/$id/business': typeof AppEditorIdBusinessRoute
  '/app/editor/$id/cta': typeof AppEditorIdCtaRoute
  '/app/editor/$id/design': typeof AppEditorIdDesignRoute
  '/app/editor/$id/details': typeof AppEditorIdDetailsRoute
  '/app/editor/$id/disclaimer': typeof AppEditorIdDisclaimerRoute
  '/app/editor/$id/social': typeof AppEditorIdSocialRoute
  '/app/editor/$id/': typeof AppEditorIdIndexRoute
  '/api/public/sig-image/$id/$kind': typeof ApiPublicSigImageIdKindRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/editor/$id/analytics': typeof AppEditorIdAnalyticsRoute
  '/app/editor/$id/business': typeof AppEditorIdBusinessRoute
  '/app/editor/$id/cta': typeof AppEditorIdCtaRoute
  '/app/editor/$id/design': typeof AppEditorIdDesignRoute
  '/app/editor/$id/details': typeof AppEditorIdDetailsRoute
  '/app/editor/$id/disclaimer': typeof AppEditorIdDisclaimerRoute
  '/app/editor/$id/social': typeof AppEditorIdSocialRoute
  '/app/editor/$id': typeof AppEditorIdIndexRoute
  '/api/public/sig-image/$id/$kind': typeof ApiPublicSigImageIdKindRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/app/admin': typeof AppAdminRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/app/editor/$id': typeof AppEditorIdRouteWithChildren
  '/app/editor/$id/analytics': typeof AppEditorIdAnalyticsRoute
  '/app/editor/$id/business': typeof AppEditorIdBusinessRoute
  '/app/editor/$id/cta': typeof AppEditorIdCtaRoute
  '/app/editor/$id/design': typeof AppEditorIdDesignRoute
  '/app/editor/$id/details': typeof AppEditorIdDetailsRoute
  '/app/editor/$id/disclaimer': typeof AppEditorIdDisclaimerRoute
  '/app/editor/$id/social': typeof AppEditorIdSocialRoute
  '/app/editor/$id/': typeof AppEditorIdIndexRoute
  '/api/public/sig-image/$id/$kind': typeof ApiPublicSigImageIdKindRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/editor/$id'
    | '/app/editor/$id/analytics'
    | '/app/editor/$id/business'
    | '/app/editor/$id/cta'
    | '/app/editor/$id/design'
    | '/app/editor/$id/details'
    | '/app/editor/$id/disclaimer'
    | '/app/editor/$id/social'
    | '/app/editor/$id/'
    | '/api/public/sig-image/$id/$kind'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/admin'
    | '/app/settings'
    | '/app'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/editor/$id/analytics'
    | '/app/editor/$id/business'
    | '/app/editor/$id/cta'
    | '/app/editor/$id/design'
    | '/app/editor/$id/details'
    | '/app/editor/$id/disclaimer'
    | '/app/editor/$id/social'
    | '/app/editor/$id'
    | '/api/public/sig-image/$id/$kind'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/mcp'
    | '/pricing'
    | '/reset-password'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/app/admin'
    | '/app/settings'
    | '/app/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/app/editor/$id'
    | '/app/editor/$id/analytics'
    | '/app/editor/$id/business'
    | '/app/editor/$id/cta'
    | '/app/editor/$id/design'
    | '/app/editor/$id/details'
    | '/app/editor/$id/disclaimer'
    | '/app/editor/$id/social'
    | '/app/editor/$id/'
    | '/api/public/sig-image/$id/$kind'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicSigImageIdKindRoute: typeof ApiPublicSigImageIdKindRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/editor/$id': {
      id: '/app/editor/$id'
      path: '/editor/$id'
      fullPath: '/app/editor/$id'
      preLoaderRoute: typeof AppEditorIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/editor/$id/': {
      id: '/app/editor/$id/'
      path: '/'
      fullPath: '/app/editor/$id/'
      preLoaderRoute: typeof AppEditorIdIndexRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/social': {
      id: '/app/editor/$id/social'
      path: '/social'
      fullPath: '/app/editor/$id/social'
      preLoaderRoute: typeof AppEditorIdSocialRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/disclaimer': {
      id: '/app/editor/$id/disclaimer'
      path: '/disclaimer'
      fullPath: '/app/editor/$id/disclaimer'
      preLoaderRoute: typeof AppEditorIdDisclaimerRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/details': {
      id: '/app/editor/$id/details'
      path: '/details'
      fullPath: '/app/editor/$id/details'
      preLoaderRoute: typeof AppEditorIdDetailsRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/design': {
      id: '/app/editor/$id/design'
      path: '/design'
      fullPath: '/app/editor/$id/design'
      preLoaderRoute: typeof AppEditorIdDesignRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/cta': {
      id: '/app/editor/$id/cta'
      path: '/cta'
      fullPath: '/app/editor/$id/cta'
      preLoaderRoute: typeof AppEditorIdCtaRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/business': {
      id: '/app/editor/$id/business'
      path: '/business'
      fullPath: '/app/editor/$id/business'
      preLoaderRoute: typeof AppEditorIdBusinessRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/app/editor/$id/analytics': {
      id: '/app/editor/$id/analytics'
      path: '/analytics'
      fullPath: '/app/editor/$id/analytics'
      preLoaderRoute: typeof AppEditorIdAnalyticsRouteImport
      parentRoute: typeof AppEditorIdRoute
    }
    '/api/public/sig-image/$id/$kind': {
      id: '/api/public/sig-image/$id/$kind'
      path: '/api/public/sig-image/$id/$kind'
      fullPath: '/api/public/sig-image/$id/$kind'
      preLoaderRoute: typeof ApiPublicSigImageIdKindRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppEditorIdRouteChildren {
  AppEditorIdAnalyticsRoute: typeof AppEditorIdAnalyticsRoute
  AppEditorIdBusinessRoute: typeof AppEditorIdBusinessRoute
  AppEditorIdCtaRoute: typeof AppEditorIdCtaRoute
  AppEditorIdDesignRoute: typeof AppEditorIdDesignRoute
  AppEditorIdDetailsRoute: typeof AppEditorIdDetailsRoute
  AppEditorIdDisclaimerRoute: typeof AppEditorIdDisclaimerRoute
  AppEditorIdSocialRoute: typeof AppEditorIdSocialRoute
  AppEditorIdIndexRoute: typeof AppEditorIdIndexRoute
}

const AppEditorIdRouteChildren: AppEditorIdRouteChildren = {
  AppEditorIdAnalyticsRoute: AppEditorIdAnalyticsRoute,
  AppEditorIdBusinessRoute: AppEditorIdBusinessRoute,
  AppEditorIdCtaRoute: AppEditorIdCtaRoute,
  AppEditorIdDesignRoute: AppEditorIdDesignRoute,
  AppEditorIdDetailsRoute: AppEditorIdDetailsRoute,
  AppEditorIdDisclaimerRoute: AppEditorIdDisclaimerRoute,
  AppEditorIdSocialRoute: AppEditorIdSocialRoute,
  AppEditorIdIndexRoute: AppEditorIdIndexRoute,
}

const AppEditorIdRouteWithChildren = AppEditorIdRoute._addFileChildren(
  AppEditorIdRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEditorIdRoute: typeof AppEditorIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppEditorIdRoute: AppEditorIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicSigImageIdKindRoute: ApiPublicSigImageIdKindRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
